---
# tasks file for helabs.ruby
- include: RedHat.yml
  when:
    ansible_os_family == 'RedHat'

- include: Debian.yml
  when:
    ansible_os_family == 'Debian'

- include: rbenv.yml
- include: ruby.yml
