---
- name: Asserting if any ruby packages are installed via rvm
  command: '{{ rvm }} {{ item }} do true'
  with_items: rvm_rubies
  when: rvm_rubies
  changed_when: False
  failed_when: False
  register: detected_rubies

- name: Installing rubies
  command: '{{ rvm }} install {{ item.item }} {{ rvm_rubies_install_flags }}'
  when: rvm_rubies and item.rc|default(0) != 0
  with_items: detected_rubies.results

- name: Asserting which is the default ruby version
  command: '{{ rvm }} alias list default'
  changed_when: False
  register: detected_default_ruby_version

- name: Setting up the correct default ruby version
  command: '{{ rvm }} alias create default {{ rvm_default_ruby_version }}'
  when: detected_default_ruby_version.stdout|default() == '' or
        rvm_default_ruby_version not in detected_default_ruby_version.stdout

- name: Asserting installed ruby patch number
  shell: >
    {{ rvm }} list strings | grep {{ item }} | tail -n 1
  with_items: rvm_rubies
  changed_when: False
  always_run: yes
  register: ruby_patch_no

- name: Installing bundler
  gem:
    name: bundler
    state: latest
    executable: '"{{ rvm_install_path }}"/rubies/"{{ rvm_default_ruby_version }}"/bin/gem'


- name: Asserting if is there any ruby versions that to be deleted
  command: '{{ rvm }} {{ rvm_rubies_to_purge }} do true'
  changed_when: False
  failed_when: False
  register: detected_rubies_to_purge
  when: rvm_rubies_to_purge

- name: Purging ruby versions
  command: '{{ rvm }} remove {{ detected_rubies_to_purge }}'
  changed_when: False
  when: rvm_rubies_to_purge and detected_rubies_to_purge.rc == 0
